color:
  brandStrength: 0.8255319
  saturation: 0.25
  brandColors:
    - '#260324'
    - '#fdfaee'
    - '#674135'
    - '#b67e6f'
    - '#eebd9d'
  lightness: 0.0625
  rhythmicContrast: 1
title: Doula in Chicago and Los Angeles
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 1
purpose: []
name: Birthquakes
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.63343
