name: Birthquakes
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63343
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: The best Doula in Chicago and Los Angeles
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#260324'
    - '#fdfaee'
    - '#674135'
    - '#b67e6f'
    - '#eebd9d'
  brandStrength: 0.8255319
  lightness: 0.0625
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
