name: Birthquakes
favicon: null
layout_spectrum: 0.33899
typography_spectrum: 0.96777
title: Doula in Chicago and Los Angeles
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a1742'
    - '#726a79'
    - '#a0908d'
    - '#cabbae'
    - '#eee6d3'
  brandStrength: 0.8125
  lightness: 0.312766
  saturation: 0.6702127
  rhythmicContrast: 0.5
purpose: []
