layout_spectrum: 1
typography_spectrum: 0.4744681
color:
  lightness: 0.7425532
  brandStrength: 0.2143434
  saturation: 0.3574468
  rhythmicContrast: 0.8851064
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: Birthquakes
