layout_spectrum: 1
name: Birthquakes
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.8255319
  lightness: 0.7425532
  saturation: 0.3574468
  rhythmicContrast: 0.8851064
  brandColors:
    - '#FFFFFF'
    - '#280426'
    - '#AC786E'
    - '#91534A'
    - '#EABDA2'
typography_spectrum: 0.4744681
